lib/zombie_apocalypse_survival_web/router.ex
defmodule ZombieApocalypseSurvivalWeb.Router do
  use ZombieApocalypseSurvivalWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ZombieApocalypseSurvivalWeb.LayoutView, :root}
    # plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :static do
    plug Plug.Static,
      at: "/uploads",
      from: "uploads/",
      gzip: false
  end

  scope "/uploads" do
    pipe_through :static

    forward "/",
            Plug.Static,
            at: "/uploads",
            from: "uploads/"
  end

  pipeline :auth do
    plug ZombieApocalypseSurvival.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", ZombieApocalypseSurvivalWeb do
    pipe_through [:browser, :auth]

    get "/", SurvivorController, :new
    post "/signup", SurvivorController, :create

    get "/login", AuthController, :new
    post "/login", AuthController, :login
    get "/logout", AuthController, :logout
  end

  scope "/", ZombieApocalypseSurvivalWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/survivors", SurvivorController, :index
    get "/home-page", SurvivorController, :home_page
    get "/survivor/edit", SurvivorController, :edit
    put "/survivor/update", SurvivorController, :update

    get "/resource", ResourceController, :new
    post "/resource", ResourceController, :create
    get "/resource/:id", ResourceController, :show

    post "/trade/:id", TradeController, :create
    get "/requests", TradeController, :show_requests
    get "/accept-request/:id", TradeController, :accept_request
    get "/reject-request/:id", TradeController, :reject_request

    get "/report", ReportController, :report_dashboard
    get "/reported/:id", ReportController, :get_reported

  end

  # Other scopes may use custom stacks.
  # scope "/api", ZombieApocalypseSurvivalWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: ZombieApocalypseSurvivalWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/zombie_apocalypse_survival/survivor_manager/survivor.ex
defmodule ZombieApocalypseSurvival.SurvivorManager.Survivor do
  use Ecto.Schema
  import Ecto.Changeset
  alias Argon2
  alias ZombieApocalypseSurvival.{ResourceManager, SurvivorManager}
  use  Waffle.Ecto.Schema

  schema "survivors" do
    field :age, :integer
    field :gender, :string
    field :name, :string
    field :password, :string
    field :email, :string
    field :survivor_flag, :boolean
    field :latitude, :float
    field :longitude, :float
    field :profile_image, ZombieApocalypseSurvival.Avatar.Type
    field :is_admin, :boolean
    has_many :resource, ResourceManager.Resource
    has_many :survivor_loc_log, SurvivorManager.SurvivorLocLog
    timestamps()
  end

  @doc false
  def changeset(survivor, attrs) do
    survivor
    |> cast(attrs, [
      :name,
      :password,
      :age,
      :gender,
      :email,
      :latitude,
      :longitude,
      :survivor_flag,
      :is_admin,
      # :profile_image
    ])
    |> cast_attachments(attrs, [:profile_image])
    |> validate_required([
      :name,
      :password,
      :age,
      :gender,
      :email,
      :latitude,
      :longitude,
    ])
    |> unique_constraint(:email)
    |> put_password_hash()
  end

  defp put_password_hash(
         %Ecto.Changeset{valid?: true, changes: %{password: password}} = changeset
       ) do
    change(changeset, password: Argon2.hash_pwd_salt(password))
  end

  defp put_password_hash(changeset), do: changeset
end

lib/zombie_apocalypse_survival_web/controllers/survivor_controller.ex
defmodule ZombieApocalypseSurvivalWeb.SurvivorController do
  use ZombieApocalypseSurvivalWeb, :controller
  alias ZombieApocalypseSurvivalWeb.AuthController

  alias ZombieApocalypseSurvival.{
    SurvivorManager,
    SurvivorManager.Survivor,
    Auth.Guardian,
    Avatar,
    Survivor_loc_log
  }


  def home_page(conn, _params) do
    render(conn, "home_page.html")
  end

  def new(conn, _params) do
    changeset = SurvivorManager.change_survivor(%Survivor{})
    maybe_user = Guardian.Plug.current_resource(conn)

    if maybe_user do
      redirect(conn, to: "/resource")
    else
      IO.inspect(changeset)
      render(conn, "signup.html",
        changeset: changeset,
        action: Routes.survivor_path(conn, :create)
      )
    end
  end

  def create(conn, %{"survivor" => params}) do
    case SurvivorManager.get_survivor_by_email(params["email"]) do
     nil ->
          # params = params
          #          |> Map.put("profile_image", params["profile_photo"])
          IO.inspect(params, label: "Signup params")

            case SurvivorManager.create_survivor(params) do
              {:ok, survivor} ->
                create_location_log(%{
                  survivor_id: survivor.id,
                  latitude: params["latitude"],
                  longitude: params["longitude"]
                })

                profile_photo_upload(params, survivor)
                AuthController.login_reply({:ok, survivor}, conn)

              {:error, changeset} ->
                # IO.inspect(changeset)
                # conn
                # |> put_flash(:error, "Some Thing Went Wrong")
                # |> new(%{})
                conn
                 |> render("signup.html", changeset: changeset, action: Routes.survivor_path(conn, :create))

            end
     _survivor ->
        conn
        |> put_flash(:error, "Email Already Registered")
        |> new(%{})

     end
  end

  # def create(conn, params) do
  #   case SurvivorManager.create_survivor(params) do
  #     {:error, %Ecto.Changeset{} = changeset} ->
  #       conn
  #       |> render("signup.html", changeset: changeset, action: Routes.survivor_path(conn, :create))
  #   end
  # end

  def create_location_log(params) do
    Survivor_loc_log.create_survivor_loc_log(params)
  end

  def profile_photo_upload(params, survivor) do
    IO.inspect(survivor, label: "Profile Photo Upload")
    %{"profile_image" => upload_plug} = params
    Avatar.store({upload_plug, survivor})
  end

  def index(conn, _params) do
    user = Guardian.Plug.current_resource(conn)
    if Bodyguard.permit(ZombieApocalypseSurvival.Policy, :survivor, user) |> IO.inspect(label: "Bodyguard") == :ok do
      render(conn, "all_survivors.html", survivors: list_survivors(), user: user)
    else
    conn
    |> put_status(:forbidden)
    |> put_view(ZombieApocalypseSurvivalWeb.ErrorView)
    |> render(:"403")

    end

  end

  defp list_survivors do
    SurvivorManager.list_survivors()
  end

  def edit(conn, _params) do
    survivor = Guardian.Plug.current_resource(conn)
    changeset = SurvivorManager.change_survivor(survivor)
    image = Avatar.url({survivor.profile_image, survivor}, :thumb)

    render(conn, "update_survivor.html",
      survivor: survivor,
      image: image,
      changeset: changeset,
      action: Routes.survivor_path(conn, :update)
    )
  end

  def update(conn, %{"survivor" => %{"profile_image" => _image} = survivor_params}) do
    IO.inspect(survivor_params, label: "survivor_params_profile")
    survivor = Guardian.Plug.current_resource(conn)
    profile_photo_upload(survivor_params, survivor)

    case SurvivorManager.update_survivor(survivor, survivor_params) do
      {:ok, _survivor} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.survivor_path(conn, :new))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "update_survivor.html", survivor: survivor, changeset: changeset, action: Routes.survivor_path(conn, :update), image: Avatar.url({survivor.profile_image, survivor}, :thumb))
    end
  end

  def update(conn, %{
        "survivor" => %{"latitude" => _latitude, "longitude" => _longitude} = survivor_params
      }) do
      IO.inspect(survivor_params, label: "survivor_params")
    survivor = Guardian.Plug.current_resource(conn)

    case SurvivorManager.update_survivor(survivor, survivor_params) do
      {:ok, _survivor} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.survivor_path(conn, :new))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "update_survivor.html", survivor: survivor, changeset: changeset, action: Routes.survivor_path(conn, :update), image: Avatar.url({survivor.profile_image, survivor}, :thumb))
    end
  end

end

lib/zombie_apocalypse_survival_web/views/survivor_view.ex
defmodule ZombieApocalypseSurvivalWeb.SurvivorView do
  use ZombieApocalypseSurvivalWeb, :view
end

lib/zombie_apocalypse_survival_web/templates/survivor/all_survivors.html.heex
<table>
  <div>
   <h2> <%= "You logged in as #{@user.name}" %> </h2>
  </div>
  <div style="display:flex;flex-direction:row; justify-content: space-between; align-items: baseline;">
  <span><%= link "Logout", to: Routes.auth_path(@conn, :logout) %></span>
  <span><%= link "Check Trade Requests", to: Routes.trade_path(@conn, :show_requests) %></span>
  <span ><%= link "Update Profile", to: Routes.survivor_path(@conn, :edit) %></span>
  </div>
  <thead>
    <tr>
      <th>Survivor Name</th>
      <th>Age</th>
      <th>Gender</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for survivor <- @survivors do %>
      <tr>
        <td><%= survivor.name %></td>
        <td><%= survivor.age %></td>
        <td><%= survivor.gender %></td>
      <td>
        <% IO.inspect(survivor) %>
        <span><%= link "Trade", to: Routes.resource_path(@conn, :show, survivor) %></span>
        <span style="float: right;"><%= link "Report", to: Routes.report_path(@conn, :get_reported, survivor) %></span>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/zombie_apocalypse_survival_web/templates/survivor/home_page.html.heex
<h1>ZombieApocalypseSurvival Home Page</h1>

  <div style="display:grid; grid-template-columns:1fr 1fr; gap: 5%">

     <div>
      <p style="text-align:justify; font-size:20px;">
           The world, as we know it, has fallen into an apocalyptic scenario. A disease is transforming human beings into violent creatures (a.k.a. Zombies)
           You, the last survivor who knows how to code, will help the resistance by deploying a system to connect the remaining humans. This system will be
           essential to detect new infections and share resources between the members.

      </p>

     </div>



      <div>

          <p style="text-align:justify; font-size:20px; font-weight:bold; font-style:italic; color:green">
          If your a Admin then see the report Dashboard otherwise click on Survivor!!!
          </p>

         <div class="form-group">
             <span><%= link "Survivor", to: Routes.resource_path(@conn, :new) %></span>
         </div>

         <div class="form-group">
              <span><%= link "Admin", to: Routes.report_path(@conn, :report_dashboard) %></span>
         </div>

     </div>

  </div>

lib/zombie_apocalypse_survival_web/templates/survivor/signup.html.heex
<div style="display:flex;flex-direction:row; justify-content: space-between; align-items: baseline;">
  <h2>Sign Up Page</h2>
  <%= link "Login", to: Routes.auth_path(@conn, :new) %>
</div>

<%= form_for @changeset, @action, [multipart: true],fn f -> %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= email_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :age, class: "control-label" %>
    <%= select f, :age, 0..120, class: "form-control" %>
    <%= error_tag f, :age %>
  </div>

  <div class="form-group">
    <%= label f, :gender, class: "control-label" %>
    <%= select f, :gender, ["Male": "male", "Female": "female"], class: "form-control" %>
    <%= error_tag f, :gender %>
  </div>

   <div class="form-group">
    <%= label f, :profile_image, class: "control-label" %>
    <%= file_input f, :profile_image, class: "form-control" %>
    <%= error_tag f, :profile_image %>
  </div>

  <div class="form-group">
    <%= label f, :latitude, class: "control-label" %>
    <%= text_input f, :latitude, class: "form-control" %>
    <%= error_tag f, :latitude %>
  </div>

  <div class="form-group">
    <%= label f, :longitude, class: "control-label" %>
    <%= text_input f, :longitude, class: "form-control" %>
    <%= error_tag f, :longitude %>
  </div>


  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/zombie_apocalypse_survival_web/templates/survivor/update_survivor.html.heex
<%= form_for @changeset, @action, [multipart: true],fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :latitude , class: "control-label" %>
  <%= text_input f, :latitude , class: "form-control" %>
  <%= error_tag f, :latitude %>

  <%= label f, :longitude, class: "control-label" %>
  <%= text_input f, :longitude , class: "form-control" %>
  <%= error_tag f, :longitude %>

  <img src={@image} alt="Profile Picture" />

  <div class="form-group">
    <%= label f, :profile_image, class: "control-label" %>
    <%= file_input f, :profile_image, class: "form-control" %>
    <%= error_tag f, :profile_image %>
  </div>


   <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>